In [19]:
import  numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [20]:
#Function importing dataset

def importdata():
    balance_data = pd.read_csv(


        'https://archive.ics.uci.edu/ml/machine-learning-'+'databases/balance-scale/balance-scale.data',

        sep = ',', header = None
    )

    print('Dataset Length:', len(balance_data))
    print('Dataset Shape:', balance_data.shape)

    return balance_data
    

In [21]:
print(importdata())

Dataset Length: 625
Dataset Shape: (625, 5)
     0  1  2  3  4
0    B  1  1  1  1
1    R  1  1  1  2
2    R  1  1  1  3
3    R  1  1  1  4
4    R  1  1  1  5
..  .. .. .. .. ..
620  L  5  5  5  1
621  L  5  5  5  2
622  L  5  5  5  3
623  L  5  5  5  4
624  B  5  5  5  5

[625 rows x 5 columns]


In [41]:
#create a function to split the dataset. 
from sklearn.model_selection import train_test_split

# create a function to split the dataset
def splitdataset(balance_data):
    # Separating the target variable
    x = balance_data.values[:, 1:5]   # features
    y = balance_data.values[:, 0]     # target

    # Splitting dataset into train and test
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.3, random_state=100)

    return x_train, x_test, y_train, y_test



In [57]:
#function to perform training with giniIndex.

def train_using_gini(x_train, y_train):
    clf_gini = DecisionTreeClassifier(
        criterion='gini',
        random_state=100,
        max_depth=3,
        min_samples_leaf=5
    )
    clf_gini.fit(x_train, y_train)
    return clf_gini

In [58]:
#Function to perform training with enropy

def train_using_entropy(x_train, y_train):
    clf_entropy = DecisionTreeClassifier(
        criterion='entropy',
        random_state=100,
        max_depth=3,
        min_samples_leaf=5
    )
    clf_entropy.fit(x_train, y_train)
    return clf_entropy

    

In [59]:
#Function to make predictions

def predictions(x_test, clf_object):

    #prediction on test with giniIndex
    y_pred = clf_object.predict(x_test)
    print('Predicted values:')
    print(y_pred)
    return y_pred

In [64]:
#Function to calculate the accuracy

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

def cal_accuracy(y_test, y_pred):
    print("Confusion Matrix :\n", confusion_matrix(y_test, y_pred))
    print("Accuracy :", accuracy_score(y_test, y_pred) * 100)
    print("Report :\n", classification_report(y_test, y_pred))


In [65]:


def main():
    data = importdata()

    # Split dataset
    x_train, x_test, y_train, y_test = splitdataset(data)
    
    # Train classifiers
    clf_gini = train_using_gini(x_train, y_train)
    clf_entropy = train_using_entropy(x_train, y_train)
    
    # Operational Phase
    print('Results Using Gini Index:')
    
    # Prediction using Gini
    y_pred_gini = predictions(x_test, clf_gini)
    cal_accuracy(y_test, y_pred_gini)
    
    print('Results Using Entropy:')
    
    # Prediction using Entropy
    y_pred_entropy = predictions(x_test, clf_entropy)
    cal_accuracy(y_test, y_pred_entropy)
    
    
if __name__ == "__main__":
    main()


Dataset Length: 625
Dataset Shape: (625, 5)
Results Using Gini Index:
Predicted values:
['R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'L'
 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R'
 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R'
 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R'
 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R'
 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'R']
Confusion Matrix :
 [[ 0  6  7]
 [ 0 67 18]
 [ 0 19 71]]
Accuracy : 73.40425531914893
Report :
               precision    recall  f1-score   suppor

/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/anaconda3/lib/python3.13/site-pa